#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 36
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

identify_chimeric_seqs.py \
-i ~/SL_out/seqs.fna \
-m usearch61 \
-o ~/US_out/ \
-r ~/silva128/rep_set/rep_set_16S_only/97/97_otus_16S.fasta

#deactivating environment
source deactivate
