#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 36
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# picking OTUs
echo "Picking OTUs with closed reference"
time pick_closed_reference_otus.py \
-i $PWD/SL_out/seqs.fna \
-o $PWD/OTU/ \
-a -O 16 


#deactivating environment
source deactivate
