#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH -n 36
#SBATCH -p normal

#Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# picking OTUs
echo "Picking OTUs with closed reference"
pick_closed_reference_otus.py \
-i ~/SL_out/seqs.fna \
-o ~/Picked_OTUs/ \
-r ~/silva128/rep_set/rep_set_16S_only/97/97_otus_16S.fasta \
-t ~/silva128/taxonomy/16S_only/97/majority_taxonomy_all_levels.txt \
-a -O 16 


#deactivating environment
source deactivate
