#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 36
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# splitting libraries
split_libraries_fastq.py \
-m ~/maps/map_complete.tsv \
-i ~/AssemR.fastq.gz \
-b ~/AssemI.fastq \
-o ~/SL_out \
-q 19 \
--rev_comp_barcode \
--rev_comp_mapping_barcodes

# deactivating environment
source deactivate
